web:
  build: .
  links:
   - db
  ports:
   - "3000:3000"
   - "35729:35729"
  volumes:
   - ./app:/home/mean/app
  environment: 
   NODE_ENV: development
db:
  image: mongo:latest
  ports: 
   - "27017:27017"